"""empty message

Revision ID: 0f67c91ac65a
Revises: 
Create Date: 2021-04-15 14:02:46.390269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f67c91ac65a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('atype', sa.String(length=20), server_default='user', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('easy_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_blueprint', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('form_parent_id', sa.Integer(), nullable=True),
    sa.Column('submit_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_parent_id'], ['easy_form.id'], ),
    sa.ForeignKeyConstraint(['submit_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_submission')
    op.drop_table('easy_form')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
