"""empty message

Revision ID: 50baeec6de14
Revises: 94325fcc2cab
Create Date: 2021-06-08 17:26:34.652912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50baeec6de14'
down_revision = '94325fcc2cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        pass

    # ### end Alembic commands ###
